// proyectos/cotizador-prestamos-react/src/components/Button.jsx
export default function Button({operator, handler}){
    return (
        <button
          type="button"
          className="h-10 w-10 flex items-center justify-center 
          font-bold text-white text-2xl bg-lime-500 
          rounded-full hover:outline-none hover:ring-2 
          hover:ring-offset-2 hover:ring-lime-500"
          onClick={handler}
        >{operator}</button>
    );
}

// proyectos/cotizador-prestamos-vue/src/components/Button.vue
<script setup>
const props = defineProps({
  operator: String,
  handleClick: Function,
});
</script>

<template>
  <button
    type="button"
    className="h-10 w-10 flex items-center justify-center 
      font-bold text-white text-2xl bg-lime-500 
      rounded-full hover:outline-none hover:ring-2 
      hover:ring-offset-2 hover:ring-lime-500"
    @click="handleClick"
  >
    {{ operator }}
  </button>
</template>
